---
apiVersion: v1
kind: Secret
metadata:
  namespace: frontend-namespace
  name: frontend-secret
data:
  PGDB_USER: cG9zdGdyZXMtdXNlcg==     # Base64 encoded "postgres"
  PGDB_PASSWORD: cG9zdGdyZXMtcHdk     # Base64 encoded "password"
