apiVersion: v1
kind: Pod
metadata:
  namespace: postgres-namespace
  name: postgres-pod
  labels:
    app: postgres-db
spec:
  containers:
  - name: postgres
    image: postgres:13
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: POSTGRES_USER
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: POSTGRES_PASSWORD
    - name: POSTGRES_DB
      valueFrom:
        configMapKeyRef:
          name: postgres-configmap
          key: POSTGRES_DB
    ports:
    - containerPort: 5432
